import { PIPELINE_THRESHOLDS } from '../config.js';
import type { PublisherInput, PublisherResult } from './types.js';

type PublisherRepository = {
  insertSheet(sheet: {
    slug: string;
    title: string;
    artistId: string;
    genreId: string;
    difficultyId: string;
    bpm: number;
    durationSeconds: number;
    noteCount: number;
    notesPerSecond: number;
    sheetData: string;
    qualityScore: number;
    isCanonical: boolean;
    canonicalSheetId: string | null;
    youtubeUrl?: string;
    thumbnailUrl: string;
    source: string;
    sourceUrl: string;
    tips?: string[] | null;
    isAutoGenerated: boolean;
    metadataConfidence: 'high' | 'medium' | 'low';
    isPublished: boolean;
    needsReview: boolean;
  }): Promise<{ id: string; slug: string }>;
  updateFingerprint(update: {
    normalizedKey: string;
    canonicalSheetId: string;
    versionCount: number;
  }): Promise<void>;
  revalidatePaths(paths: string[]): Promise<void>;
};

function getConfidenceBand(score: number): 'high' | 'medium' | 'low' {
  if (score >= 0.8) {
    return 'high';
  }

  if (score >= 0.5) {
    return 'medium';
  }

  return 'low';
}

export function determinePublicationOutcome(qualityScore: number, confidenceScore: number): Exclude<PublisherResult['outcome'], 'dry_run'> {
  if (qualityScore < PIPELINE_THRESHOLDS.review) {
    return 'rejected';
  }

  if (qualityScore >= PIPELINE_THRESHOLDS.publish && confidenceScore >= 0.8) {
    return 'published';
  }

  return 'needs_review';
}

function buildRevalidationPaths(input: PublisherInput): string[] {
  return [
    '/',
    '/catalog',
    `/artist/${input.artist.slug}`,
    `/genre/${input.genre.slug}`,
    `/sheet/${input.slug}`,
  ];
}

export async function publishSheet(input: PublisherInput, repository: PublisherRepository): Promise<PublisherResult> {
  const outcome = determinePublicationOutcome(input.qualityScore, input.confidenceScore);

  if (outcome === 'rejected') {
    return {
      outcome,
      sheetId: null,
      revalidatedPaths: [],
    };
  }

  if (input.dryRun) {
    return {
      outcome: 'dry_run',
      sheetId: null,
      revalidatedPaths: [],
    };
  }

  const insertedSheet = await repository.insertSheet({
    slug: input.slug,
    title: input.title,
    artistId: input.artist.id,
    genreId: input.genre.id,
    difficultyId: input.difficulty.id,
    bpm: input.bpm,
    durationSeconds: input.durationSeconds,
    noteCount: input.noteCount,
    notesPerSecond: input.notesPerSecond,
    sheetData: input.sheetData,
    qualityScore: input.qualityScore,
    isCanonical: input.isCanonical,
    canonicalSheetId: input.canonicalSheetId,
    youtubeUrl: input.youtubeUrl,
    thumbnailUrl: input.thumbnailUrl,
    source: input.source,
    sourceUrl: input.sourceUrl,
    tips: input.tips ?? null,
    isAutoGenerated: true,
    metadataConfidence: getConfidenceBand(input.confidenceScore),
    isPublished: outcome === 'published',
    needsReview: outcome === 'needs_review',
  });

  await repository.updateFingerprint({
    normalizedKey: input.normalizedKey,
    canonicalSheetId: insertedSheet.id,
    versionCount: input.nextVersionCount,
  });

  const revalidatedPaths = outcome === 'published' ? buildRevalidationPaths(input) : [];
  if (revalidatedPaths.length > 0) {
    await repository.revalidatePaths(revalidatedPaths);
  }

  return {
    outcome,
    sheetId: insertedSheet.id,
    revalidatedPaths,
  };
}