import { PIPELINE_THRESHOLDS } from "../config.js";
import type { DifficultyLevel } from "@zen/midi-to-vp";
import type { SourceDifficultyLabel } from "./canonical-selector.js";
import type { PublisherInput, PublisherResult } from "./types.js";

type PublisherRepository = {
  insertSheet(sheet: {
    slug: string;
    title: string;
    artistId: string;
    genreId: string;
    difficultyId: string;
    bpm: number;
    durationSeconds: number;
    noteCount: number;
    notesPerSecond: number;
    sheetData: string;
    qualityScore: number;
    isCanonical: boolean;
    canonicalSheetId: string | null;
    youtubeUrl?: string;
    thumbnailUrl: string;
    source: string;
    sourceUrl: string;
    tips?: string[] | null;
    isAutoGenerated: boolean;
    metadataConfidence: "high" | "medium" | "low";
    isPublished: boolean;
    needsReview: boolean;
    workId?: string | null;
    arrangementId?: string | null;
    sourceDifficultyLabel?: SourceDifficultyLabel | null;
    conversionLevel?: DifficultyLevel | null;
  }): Promise<{ id: string; slug: string }>;
  updateFingerprint(update: {
    normalizedKey: string;
    canonicalSheetId: string;
    versionCount: number;
  }): Promise<void>;
  promoteCanonicalFamily(input: {
    previousCanonicalSheetId: string;
    nextCanonicalSheetId: string;
  }): Promise<void>;
  revalidatePaths(paths: string[]): Promise<void>;
};

function getConfidenceBand(score: number): "high" | "medium" | "low" {
  if (score >= 0.8) {
    return "high";
  }

  if (score >= 0.5) {
    return "medium";
  }

  return "low";
}

export function determinePublicationOutcome(
  qualityScore: number,
  confidenceScore: number,
): Exclude<PublisherResult["outcome"], "dry_run"> {
  if (qualityScore < PIPELINE_THRESHOLDS.review) {
    return "rejected";
  }

  if (qualityScore >= PIPELINE_THRESHOLDS.publish && confidenceScore >= 0.8) {
    return "published";
  }

  return "needs_review";
}

function buildRevalidationPaths(input: PublisherInput): string[] {
  return [
    "/",
    "/catalog",
    `/artist/${input.artist.slug}`,
    `/genre/${input.genre.slug}`,
    `/sheet/${input.slug}`,
  ];
}

function normalizePersistedInteger(value: number): number {
  return Math.round(value);
}

function assertPublisherInvariant(id: string, field: string): void {
  if (!id) {
    throw new Error(`publisher invariant: missing ${field}`);
  }
}

export async function publishSheet(
  input: PublisherInput,
  repository: PublisherRepository,
): Promise<PublisherResult> {
  const outcome = determinePublicationOutcome(
    input.qualityScore,
    input.confidenceScore,
  );

  if (outcome === "rejected") {
    return {
      outcome,
      sheetId: null,
      revalidatedPaths: [],
    };
  }

  if (input.dryRun) {
    return {
      outcome: "dry_run",
      sheetId: null,
      revalidatedPaths: [],
    };
  }

  assertPublisherInvariant(input.artist.id, "artist.id");
  assertPublisherInvariant(input.genre.id, "genre.id");
  assertPublisherInvariant(input.difficulty.id, "difficulty.id");

  const insertedSheet = await repository.insertSheet({
    slug: input.slug,
    title: input.title,
    artistId: input.artist.id,
    genreId: input.genre.id,
    difficultyId: input.difficulty.id,
    bpm: normalizePersistedInteger(input.bpm),
    durationSeconds: normalizePersistedInteger(input.durationSeconds),
    noteCount: input.noteCount,
    notesPerSecond: input.notesPerSecond,
    sheetData: input.sheetData,
    qualityScore: input.qualityScore,
    isCanonical:
      outcome !== "published" && input.canonicalSheetId !== null
        ? false
        : input.isCanonical,
    canonicalSheetId: input.canonicalSheetId,
    youtubeUrl: input.youtubeUrl,
    thumbnailUrl: input.thumbnailUrl,
    source: input.source,
    sourceUrl: input.sourceUrl,
    tips: input.tips ?? null,
    isAutoGenerated: true,
    metadataConfidence: getConfidenceBand(input.confidenceScore),
    isPublished: outcome === "published",
    needsReview: outcome === "needs_review",
    workId: input.workId ?? null,
    arrangementId: input.arrangementId ?? null,
    sourceDifficultyLabel: input.sourceDifficultyLabel ?? null,
    conversionLevel: input.conversionLevel ?? null,
  });

  if (
    outcome === "published" &&
    input.isCanonical &&
    input.canonicalSheetId !== null
  ) {
    await repository.promoteCanonicalFamily({
      previousCanonicalSheetId: input.canonicalSheetId,
      nextCanonicalSheetId: insertedSheet.id,
    });
  }

  const fingerprintCanonicalSheetId =
    outcome === "published" &&
    (input.isCanonical || input.canonicalSheetId === null)
      ? insertedSheet.id
      : (input.canonicalSheetId ?? insertedSheet.id);

  await repository.updateFingerprint({
    normalizedKey: input.normalizedKey,
    canonicalSheetId: fingerprintCanonicalSheetId,
    versionCount: input.nextVersionCount,
  });

  const revalidatedPaths =
    outcome === "published" ? buildRevalidationPaths(input) : [];
  if (revalidatedPaths.length > 0) {
    try {
      await repository.revalidatePaths(revalidatedPaths);
    } catch {
      // Revalidation is best-effort after durable writes succeed.
    }
  }

  return {
    outcome,
    sheetId: insertedSheet.id,
    revalidatedPaths,
  };
}
