import { PIPELINE_THRESHOLDS } from "../config.js";
import type { DifficultyLevel } from "@zen/midi-to-vp";
import type { SourceDifficultyLabel } from "./canonical-selector.js";
import type { PublisherInput, PublisherResult } from "./types.js";

type PublisherRepository = {
  insertSheet(sheet: {
    slug: string;
    title: string;
    artistId: string;
    genreId: string;
    difficultyId: string;
    bpm: number;
    durationSeconds: number;
    noteCount: number;
    notesPerSecond: number;
    sheetData: string;
    qualityScore: number;
    isCanonical: boolean;
    canonicalSheetId: string | null;
    youtubeUrl?: string;
    thumbnailUrl: string;
    source: string;
    sourceUrl: string;
    tips?: string[] | null;
    isAutoGenerated: boolean;
    generationMode: "standard" | "forced";
    forcePublish: boolean;
    forcedAt: Date | null;
    forceReason: string | null;
    forceContext: Record<string, unknown> | null;
    metadataConfidence: "high" | "medium" | "low";
    isPublished: boolean;
    needsReview: boolean;
    workId?: string | null;
    arrangementId?: string | null;
    sourceDifficultyLabel?: SourceDifficultyLabel | null;
    conversionLevel?: DifficultyLevel | null;
  }): Promise<{ id: string; slug: string }>;
  updateFingerprint(update: {
    normalizedKey: string;
    canonicalSheetId: string;
    versionCount: number;
  }): Promise<void>;
  promoteCanonicalFamily(input: {
    previousCanonicalSheetId: string;
    nextCanonicalSheetId: string;
  }): Promise<void>;
  revalidatePaths(paths: string[]): Promise<void>;
};

function getConfidenceBand(score: number): "high" | "medium" | "low" {
  if (score >= 0.8) {
    return "high";
  }

  if (score >= 0.5) {
    return "medium";
  }

  return "low";
}

export function determinePublicationOutcome(
  qualityScore: number,
  confidenceScore: number,
): Exclude<PublisherResult["outcome"], "dry_run"> {
  if (qualityScore < PIPELINE_THRESHOLDS.review) {
    return "rejected";
  }

  if (qualityScore >= PIPELINE_THRESHOLDS.publish && confidenceScore >= 0.8) {
    return "published";
  }

  return "needs_review";
}

function buildRevalidationPaths(input: PublisherInput): string[] {
  return [
    "/",
    "/catalog",
    `/artist/${input.artist.slug}`,
    `/genre/${input.genre.slug}`,
    `/sheet/${input.slug}`,
  ];
}

function slugSegment(value: string): string {
  return value
    .toLocaleLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function sourceSlugDiscriminator(sourceUrl: string): string | null {
  try {
    const url = new URL(sourceUrl);
    const scoreId = url.pathname.match(/\/scores\/([^/?#]+)/)?.[1];
    if (scoreId) return slugSegment(scoreId);

    const lastPathSegment = url.pathname.split("/").filter(Boolean).at(-1);
    return lastPathSegment ? slugSegment(lastPathSegment) : null;
  } catch {
    return null;
  }
}

function buildPersistedSlug(input: PublisherInput): string {
  if (!input.arrangementId && !input.conversionLevel) {
    return input.slug;
  }

  const suffix = [
    input.sourceDifficultyLabel,
    input.conversionLevel,
    sourceSlugDiscriminator(input.sourceUrl) ?? input.arrangementId ?? null,
  ]
    .filter((part): part is string => typeof part === "string" && part.length > 0)
    .map(slugSegment)
    .filter(Boolean)
    .join("-");

  return suffix ? `${input.slug}-${suffix}` : input.slug;
}

function buildRevalidationPathsForSlug(
  input: PublisherInput,
  sheetSlug: string,
): string[] {
  return buildRevalidationPaths({ ...input, slug: sheetSlug });
}

function normalizePersistedInteger(value: number): number {
  return Math.round(value);
}

function assertPublisherInvariant(id: string, field: string): void {
  if (!id) {
    throw new Error(`publisher invariant: missing ${field}`);
  }
}

export async function publishSheet(
  input: PublisherInput,
  repository: PublisherRepository,
): Promise<PublisherResult> {
  const outcome =
    input.generationMode === "forced"
      ? input.forcePublish
        ? "published"
        : "needs_review"
      : determinePublicationOutcome(input.qualityScore, input.confidenceScore);

  if (outcome === "rejected") {
    return {
      outcome,
      sheetId: null,
      revalidatedPaths: [],
    };
  }

  if (input.dryRun && input.generationMode !== "forced") {
    return {
      outcome: "dry_run",
      sheetId: null,
      revalidatedPaths: [],
    };
  }

  assertPublisherInvariant(input.artist.id, "artist.id");
  assertPublisherInvariant(input.genre.id, "genre.id");
  assertPublisherInvariant(input.difficulty.id, "difficulty.id");

  const persistedSlug = buildPersistedSlug(input);

  const insertedSheet = await repository.insertSheet({
    slug: persistedSlug,
    title: input.title,
    artistId: input.artist.id,
    genreId: input.genre.id,
    difficultyId: input.difficulty.id,
    bpm: normalizePersistedInteger(input.bpm),
    durationSeconds: normalizePersistedInteger(input.durationSeconds),
    noteCount: input.noteCount,
    notesPerSecond: input.notesPerSecond,
    sheetData: input.sheetData,
    qualityScore: input.qualityScore,
    isCanonical:
      outcome !== "published" && input.canonicalSheetId !== null
        ? false
        : input.isCanonical,
    canonicalSheetId: input.canonicalSheetId,
    youtubeUrl: input.youtubeUrl,
    thumbnailUrl: input.thumbnailUrl,
    source: input.source,
    sourceUrl: input.sourceUrl,
    tips: input.tips ?? null,
    isAutoGenerated: true,
    generationMode: input.generationMode ?? "standard",
    forcePublish: input.forcePublish ?? false,
    forcedAt: input.forcedAt ?? null,
    forceReason: input.forceReason ?? null,
    forceContext: input.forceContext ?? null,
    metadataConfidence: getConfidenceBand(input.confidenceScore),
    isPublished: outcome === "published",
    needsReview:
      input.generationMode === "forced"
        ? !input.forcePublish
        : outcome === "needs_review",
    workId: input.workId ?? null,
    arrangementId: input.arrangementId ?? null,
    sourceDifficultyLabel: input.sourceDifficultyLabel ?? null,
    conversionLevel: input.conversionLevel ?? null,
  });

  if (
    outcome === "published" &&
    input.isCanonical &&
    input.canonicalSheetId !== null
  ) {
    await repository.promoteCanonicalFamily({
      previousCanonicalSheetId: input.canonicalSheetId,
      nextCanonicalSheetId: insertedSheet.id,
    });
  }

  const fingerprintCanonicalSheetId =
    outcome === "published" &&
    (input.isCanonical || input.canonicalSheetId === null)
      ? insertedSheet.id
      : (input.canonicalSheetId ?? insertedSheet.id);

  await repository.updateFingerprint({
    normalizedKey: input.normalizedKey,
    canonicalSheetId: fingerprintCanonicalSheetId,
    versionCount: input.nextVersionCount,
  });

  const revalidatedPaths =
    outcome === "published"
      ? buildRevalidationPathsForSlug(input, insertedSheet.slug)
      : [];
  if (revalidatedPaths.length > 0) {
    try {
      await repository.revalidatePaths(revalidatedPaths);
    } catch {
      // Revalidation is best-effort after durable writes succeed.
    }
  }

  return {
    outcome,
    sheetId: insertedSheet.id,
    revalidatedPaths,
  };
}
